### ISSUE TITLE
Dashborda kısmına ekleme konusunda hangi

### ISSUE THREAD

**Issue by mehmetyuksel101** [poisondima/Roidmi-EVE-Plus#1]
Dashborda kısmına ekleme konusunda hangi kosyayı nereye eklememiz gerkeiyor yardımcı olabilirmisin.

**Comment by poisondima** [comment]
I use one big file "ui-lovelace.yaml" to split it up into several, and put it in a separate folder.
You can take the contents of the "[ui-lovelace/5_vacuum.yaml](https://github.com/poisondima/Roidmi-EVE-Plus/blob/main/ui-lovelace/5_vacuum.yaml)" file and put it in your "ui-lovelace.yaml" file.
You can read more about it [here](https://www.home-assistant.io/lovelace/dashboards/).
