### ISSUE TITLE
xiaomi_cloud_did

### ISSUE THREAD

**Issue by vasyna** [poisondima/Roidmi-EVE-Plus#11]
А где взять xiaomi_cloud_did? Спасибо.

**Comment by vasyna** [comment]
Нашел. Xiaomi cloud token extractor его сообщает. https://stupidhouse.ru/node/32/

**Comment by jaegerschnitzel** [comment]
Much easier way to get the did: https://github.com/ApplY3D/mi-home-toolkit/releases
