### ISSUE TITLE
Расходные материалы

### ISSUE THREAD

**Issue by IvAn-72** [poisondima/Roidmi-EVE-Plus#4]
У меня ругается 
ui-lovelace.yaml
          - sensor.vacuum_cleaner_brush_cleaner_brush_life_level
          - sensor.vacuum_cleaner_brush_cleaner_brush_left_time
          - sensor.vacuum_cleaner_brush_cleaner_brush_life_level_2
          - sensor.vacuum_cleaner_brush_cleaner_brush_left_time_2
          - sensor.vacuum_cleaner_brush_cleaner_brush_life_level_3
          - sensor.vacuum_cleaner_brush_cleaner_brush_left_time_3
          - sensor.vacuum_cleaner_filter_filter_life_level
          - sensor.vacuum_cleaner_filter_filter_left_time
Правильно так
          - sensor.vacuum_cleaner_brush_life_level
          - sensor.vacuum_cleaner_brush_left_time
          - sensor.vacuum_cleaner_brush_life_level_2
          - sensor.vacuum_cleaner_brush_left_time_2
          - sensor.vacuum_cleaner_brush_life_level_3
          - sensor.vacuum_cleaner_brush_left_time_3
          - sensor.vacuum_cleaner_filter_life_level
          - sensor.vacuum_cleaner_filter_left_time

**Comment by poisondima** [comment]
Исправил
