### ISSUE TITLE
уборка комнаты

### ISSUE THREAD

**Issue by bisquit2003** [poisondima/Roidmi-EVE-Plus#6]
Здравствуйте
отправляю по вашей команде скриптом пылесос в комнату, он едет, но ха ругается, скрины из лога, 2 ошибки
после этого перестают работать другие скрипты, не связанные с миот (например голосовые озвучки от алисы)
![image](https://user-images.githubusercontent.com/98059406/187533277-8eb3a5f5-1c17-4dbe-a719-b19f70d4bf10.png)
![image](https://user-images.githubusercontent.com/98059406/187533353-13a30c19-2787-4dce-8eeb-c03a8db59dfa.png)

подскажите, может с синтаксисом что-то не так, вот мой скрипт:
![image](https://user-images.githubusercontent.com/98059406/187533632-cf915a12-7aa3-4dc8-af17-e780b6ce680e.png)

**Comment by poisondima** [comment]
Добрый день, не могу подсказать т.к. не использую компонент **xiaomi_miot_raw** для связи с облаком.
Пробуйте обратиться к автору и уточнить параметры вызова сервиса **call_action**
